description: Runs pi agent

inputs:
  issue_number:
    description: Issue number
    required: true
  model:
    description: Issue number
    required: true
  models_json:
    description: Issue number
    required: true
  token:
    description: Token
    required: true

name: forgejo-agent

runs:
  image: docker://git.zarantonello.dev/infra/forgejo-agent:1.0.8
  using: docker
