description: Responds to comments mentioning the username of the agent

inputs:
  auth-token:
    description: Token for authentication
    required: true
  auth-username:
    description: Username to which the bot responds
    required: true
  git-author:
    description: Author for git commits
    required: true
  git-email:
    description: Email for git commits
    required: true

name: forgejo-agent

runs:
  steps:
    - env:
        VERSION: v1.2.5
      name: Fetch the forgejo-agent binary
      run: |
        CACHE="/cache/forgejo-agent/$VERSION/forgejo-agent"

        if [ -f "$CACHE" ]; then
          echo "Cache Hit! Copying from tool cache..."
        else
          echo "Cache Miss! Downloading..."
          mkdir -p "/cache/forgejo-agent/$VERSION/"
          curl -o "$CACHE" "https://git.zarantonello.dev/api/packages/infra/generic/forgejo-agent/$VERSION/forgejo-agent"
        fi

        cp "$CACHE" ./forgejo-agent
        chmod +x forgejo-agent
      shell: sh
      # Valid events are:
      # - issue_opened
      # - issue_comment_created
      # - pull_request_opened
      # - pull_request_review_requested
    - name: Run forgejo-agent
      run: |
        export CTX_EVENT_NAME="${{ forge.event_name }}_${{ forge.event.action }}"

        case "$CTS_EVENT_NAME" in
          pull_request_review_requested)
            export CTX_ISSUE_NUMBER="${{ forge.event.pull_request.number }}"
            if [ "${{  forge.event.requested_reviewer.username" != "${{ inputs.auth-username }}" ]
              echo "@${{ inputs.auth-username }}" was not requested for review"
              exit 0
            fi
            ;;
          pull_request_opened)
            export CTX_ISSUE_NUMBER="${{ forge.event.pull_request.number }}"
            if [ ! echo "${{ forge.event.pull_request.body }}" | grep "${{ inputs.auth-username }}" ]
              echo "@${{ inputs.auth-username }}" was not requested for review"
              exit 0
            fi
            ;;
          issue_comment_created)
            export CTX_ISSUE_NUMBER="${{ forge.event.issue.number }}"
            if [ ! echo "${{ forge.event.comment.body }}" | grep "${{ inputs.auth-username }}" ]
              echo "@${{ inputs.auth-username }}" was not requested for review"
              exit 0
            fi
            ;;
          issues_opened)
            export CTX_ISSUE_NUMBER="${{ forge.event.issue.number }}"
            if [ ! echo "${{ forge.event.issue.body }}" | grep "${{ inputs.auth-username }}" ]
              echo "@${{ inputs.auth-username }}" was not requested for review"
              exit 0
            fi
            ;;
        esac

        export CTX_AUTH_TOKEN="${{ inputs.auth-token }}"
        export CTX_AUTH_USERNAME="${{ inputs.auth-username }}"

        # Set author and email if the bot decides to commit its changes.
        git config --global user.name "${{ inputs.git-author }}"
        git config --global user.email "${{ inputs.git-email }}"

        ./forgejo-agent
      shell: sh
  using: composite
