services:
  forgejo:
    environment:
      FORGEJO__security__INSTALL_LOCK: "true"
      FORGEJO__server__HTTP_PORT: "3000"
      FORGEJO__server__ROOT_URL: ${FORGEJO_ROOT_URL:-http://localhost:3000/}
      FORGEJO__service__DISABLE_REGISTRATION: "true"
    healthcheck:
      interval: 2s
      retries: 30
      test:
        - CMD
        - curl
        - -sf
        - http://localhost:3000/api/v1/version
      timeout: 2s
    image: codeberg.org/forgejo/forgejo:15.0.3
    ports:
      - 3000:3000
    volumes:
      - forgejo-test-data:/data

volumes:
  forgejo-test-data: {}
