concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  build:
    container:
      image: git.zarantonello.dev/infra/ci-forgejo-agent:ci@sha256:925a1b2b570f5ee051c4b6c124b69c9e3ed9aec813a44f924749e848b116664f
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Build the executable
    runs-on: srv-0-nbg-hetz
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Upload the package
        run: |
          curl -s \
            -H "Authorization: Bearer ${{ secrets.REGISTRY_PASSWORD }}" \
            --upload-file dist/forgejo-agent \
            https://git.zarantonello.dev/api/packages/infra/generic/forgejo-agent/${{ forge.ref_name }}/forgejo-agent

name: build.yaml

"on":
  push:
    tags:
      - "*"
