concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/projects/forgejo-agent:ci@sha256:bc9075c2e8f3a496d34f90ee37f8e1df3f0fda6b336b254680927f3c3f8df44e
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Checks with linters
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run linter
        run: pnpm run lint:check

name: check-linter.yaml

"on":
  pull_request:
    branches:
      - main
