concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/projects/forgejo-agent-ci:v2026.08.27.1@sha256:b16d47dda5992a423df060f4101f3eb71b8bc4cdb81867e68e749b466a774e3e
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Checks with formatters
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run formatter
        run: pnpm run format:check

name: check-formatter.yaml

"on":
  pull_request:
    branches:
      - main
