concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci-pnpm:v1.1.17@sha256:ef6e3eef8f44d9c2708fc215e1a78efc05c7f961f8fef09c5f1d97374fd05b97
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Checks with linters
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run linter
        run: pnpm run lint:check

name: check-linter.yaml

"on":
  pull_request:
    branches:
      - main
