jobs:
  respond:
    container:
      image: git.zarantonello.dev/infra/ci-forgejo-agent:ci@sha256:4afc9384b174bf55a831d87bc1929cc7e58c6796bbf5c1276cc2ba44368df164
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-ci-forgejo-agent:/cache/ci-forgejo-agent
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: LLM Bot response generation
    runs-on: srv-0-thi-home
    steps:
      - name: Configure pi
        run: |
          mkdir -p $HOME/.pi/agent/
          echo '{"providers":{"llama-server":{"baseUrl":"http://llama.zarantonello.dev/v1","api":"openai-completions","apiKey":"llama","models":[{"id":"Qwen3.6-35B-A3B","contextWindow":65536}]}}}' > $HOME/.pi/agent/models.json
      - name: Generate response
        uses: https://git.zarantonello.dev/infra/ci-forgejo-agent@dc1c6902d9b2af7cbb0f119d470b95b4a710bb4e # v1.4.0
        with:
          auth-token: ${{ secrets.AGENT_TOKEN }}
          auth-username: llm-bot
          git-author: LLM [bot]
          git-email: llm-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
