jobs:
  respond:
    container:
      image: git.zarantonello.dev/infra/ci-pnpm:v1.1.8@sha256:e124501d6e8f1e75bb10e9c0e4198f220d37d02c860866ce07e21c87bc6bb886
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-forgejo-agent:/cache/forgejo-agent
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: LLM Bot response generation
    runs-on: srv-generic
    steps:
      - name: Configure pi
        run: |
          mkdir -p ~/.pi/agent/

          cat << 'EOF' > ~/.pi/agent/auth.json
          ${{ secrets.PI_AUTH_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/models.json
          ${{ vars.PI_MODELS_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/settings.json
          ${{ vars.PI_SETTINGS_JSON }}
          EOF
      - name: Generate response
        uses: https://git.zarantonello.dev/projects/forgejo-agent@2d580939662471069eaf0661dc0013b4ac83a7dd # v1.11.2
        with:
          auth-token: ${{ secrets.CI_BOT_TOKEN }}
          auth-username: ci-bot
          git-author: CI [bot]
          git-email: ci-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
