jobs:
  respond:
    container:
      image: git.zarantonello.dev/infra/ci-forgejo-agent:ci@sha256:925a1b2b570f5ee051c4b6c124b69c9e3ed9aec813a44f924749e848b116664f
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-ci-forgejo-agent:/cache/ci-forgejo-agent
    name: LLM Bot response generation
    runs-on: srv-0-thi-home
    steps:
      - name: Configure pi
        run: |
          mkdir -p $HOME/.pi/agent/
          echo '{"providers":{"llama-server":{"baseUrl":"http://llama.zarantonello.dev/v1","api":"openai-completions","apiKey":"llama","models":[{"id":"Qwen3.6-35B-A3B","contextWindow":65536}]}}}' > $HOME/.pi/agent/models.json
      - name: Generate response
        uses: https://git.zarantonello.dev/infra/ci-forgejo-agent@9305358d8ce3ed8a2d2f20149d82b747cfb004bd # v1.3.12
        with:
          auth-token: ${{ secrets.AGENT_TOKEN }}
          auth-username: llm-bot
          git-author: LLM [bot]
          git-email: llm-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
