services:
  workspace:
    entrypoint: sleep infinity
    image: git.zarantonello.dev/infra/forgejo-agent:ci@sha256:e1f2da0087b9cb8986dbb12b72262ad966ec41eae28d82107821f92f0cd3b45c
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
