services:
  workspace:
    entrypoint: sleep infinity
    image: git.zarantonello.dev/projects/forgejo-agent:ci@sha256:bdfbbe5123e37de0aef6ed8ca83e07ed233238926bbcd0edc69b0b01cf1787b8
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
