services:
  workspace:
    entrypoint: sleep infinity
    image: git.zarantonello.dev/infra/ci-pnpm:v1.0.1@sha256:cc0fe239caf067d0270705aad16089a25383a9e76e0b98aa5966164c8cb19984
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
